theme: minima
repository: sorskoot/thestreamshack
plugins:
  - jekyll-paginate
  - kramdown
  - jemoji
  - rouge
  - sass

baseurl: ""
paginate: 5
paginate_path: "page:num"
lang: en

# twitter_username: sorskoot
# social:
#   name: Sorskoot
#   links:
#     - https://twitter.com/Sorskoot
#     - https://www.linkedin.com/in/TimmyKokke
#     - https://aboutme.google.com/b/104315803956337916111/
#     - https://github.com/sorskoot
#     - https://www.youtube.com/channel/UCayeDJg8BIIKvTdiv6Hx4zQ/
# twitter:
#   username: sorskoot
#   card: summary
  
# Build settings
sass:
  sass_dir: _sass
  style: :compressed
markdown: kramdown
exclude:
  - README.md
  - package.json
default:
  - scope:
      path: "assets/post_img"
    values:
      image: true

disclaimer: As an Amazon Associate I earn from qualifying purchases.